Add ability to specify login information for Helm repository
rossumai/chart-updater pull request #11
Opened 2022-02-10 09:31 UTC by mihuross

2022-02-10 09:54 UTC, pinkavaj requested changes

2022-02-10 09:54 UTC, pinkavaj commented on chart-updater.py
> +@click.option("--helm-repo-password", help="Helm repo user to login.", default=lambda: os.environ.get("HELM_REPO_PASSWORD", ""))
NIT `help="Helm repo user to login."` The description should likely mention password?

2022-02-10 10:03 UTC, mihuross commented on chart-updater.py
> +@click.option("--helm-repo-password", help="Helm repo user to login.", default=lambda: os.environ.get("HELM_REPO_PASSWORD", ""))
yeah, fixed.

2022-02-15 08:21 UTC, pinkavaj commented on chart-updater.py
> +@click.option("--helm-repo-password", help="Helm repo HTTP AUth password.", default=lambda: os.environ.get("HELM_REPO_PASSWORD", ""))
NIT: `AUth` -> `Auth`, pls.

2022-02-15 08:24 UTC, pinkavaj requested changes
Pls can you fix that small typo?

2022-02-15 10:10 UTC, merged